project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings  
from django.conf.urls.static import static
from app import views

urlpatterns = [
    # Examples:
    # url(r'^$', 'project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^sport_list/' , 'app.views.sport_list'),
    # url(r'^athlete_list/' , 'app.views.athlete_list'),
    url(r'^athlete_list/(?P<pk>\d+)', 'app.views.athlete_list'),
    url(r'^athlete_detail/(?P<pk>\d+)/', 'app.views.athlete_detail'),
    url(r'^about_view/$', 'app.views.about_view'),
    url(r'^events_view/$', 'app.views.events_view'),
    # url(r'^home_view/$', 'app.views.home_view'),
    url(r'^contact/$', 'app.views.contact'),
    # url(r'^base/$', 'app.views.base'),
    url(r'^signup/$', 'app.views.signup'),
    url(r'^login_view/$', 'app.views.login_view'),
    url(r'^logout_view/$', 'app.views.logout_view'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone  
from django.utils.http import urlquote  
from django.core.mail import send_mail  
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model

# Create your models here.

class Sport(models.Model):
    name = models.CharField(max_length=200)

    def __unicode__(self):
        return "%s" % self.name 

class Athlete(models.Model):
    name = models.CharField(max_length= 255)
    gender = models.CharField(max_length= 50)
    level = models.CharField(max_length= 50)
    age = models.IntegerField(null=True, blank=True)
    budget = models.FloatField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    type = models.ForeignKey('app.Sport', null=True, blank=True)
    link = models.URLField(max_length=200, blank=True, null=True)
    image = models.ImageField(upload_to="", null=True, blank=True)
    

    def __unicode__(self):
        return "%s" % self.name  



## Managing sign in:

class CustomeUserManager(BaseUserManager):

    def _create_user(self, email, username, password, is_staff, is_superuser, **extra_fields):
        now = timezone.now()
        if not email:
            raise ValueError("Email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email,
                            username=username,
                            is_staff=is_staff,
                            is_active=True,
                            is_superuser=is_superuser,
                            last_login=now,
                            date_joined=now,
                            **extra_fields
                            )
        user.set_password(password)
        user.save(using=self._db)
        return user 
    def create_user (self, email, username, password=None, **extra_fields):
        return self._create_user(email, username, password, False, False, **extra_fields)

    def create_superuser(self, email, username, password, **extra_fields):
        return self._create_user(email, username, password, True, True, **extra_fields)    



class CustomUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(null=True, blank=True, max_length=50)
    email = models.EmailField('email address', max_length=200, unique=True)
    first_name = models.CharField('first name', max_length=50, null=True, blank=True)
    last_name = models.CharField('last name', max_length=50, null=True, blank=True)
    is_staff = models.BooleanField('staff status', default=False)
    # date_joined = models.DateTimeField('date joined', auto_now_add=True)
    date_joined = models.DateTimeField(('date joined'), default=timezone.now)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    # User = get_user_model()
    objects = CustomeUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'

    def get_absolute_url(self):
        return "/users/%s/" % urlquote(self.email)

    def get_full_name(self):
        full_name = '%s %s' % (self.first_name, self.last_name)

    def get_short_name(self):
        return self.first_name

    def email_user(self, subject, message, from_email=None):
        send_mail(subject, message, from_email, [self.email])

app/templates/about.html
{% extends 'base.html'%}
{% load staticfiles %}

{% block content %}

   <!-- Page Content -->
    <div class="container">

        <!-- Marketing Icons Section -->
        <div class="row">
            <div class="col-lg-12" style="text-align: left; font-size: 10px; color: #818181;">
                <h1 class="page-header">
                
                    <font size="6" color="#8B9F3E">ABOUT US</font>
                    <br>
                    <br>
                    <font size="5" color="#818181"> A spontaneous group of athletes, developers, business men and marketers all looking towards one thing: the future.
                    Reyathena is a group of talented visionaries coming together to fill in the gap between competing athletes and sponsors. Linking the two we believe we can make legends out of passionate athletes. We believe we can broaden sponsors horizons with the opportunity we present them; the opportunity to help make history.
                    

                    <br>
                    <br>
                    Most importantly, we believe in dreams and would want nothing more than to be the reason a dream comes true.  
                </font>
                </h1>
            </div>     
        </div>
     </div>    

{% endblock %} 

app/templates/athlete_detail.html
{% extends 'base.html'%}
{% load staticfiles %}

{% block content %}
<!-- Page Content -->
    <div class="container">

        <!-- Marketing Icons Section -->
        <div class="row">
            <div class="col-lg-12" style= 'margin-top: 150px'>
                <h1 class="page-header">
                    <font size="6" color="#8B9F3E">PROFILE</font>
                </h1>
            </div>     
        </div>
    
       <a href="/athlete_list/1/"><button>Back</button> </a>   

        
        <p>Name: {{athlete.name}}</p>
        <p>Gender: {{athlete.gender}}</p> 
        <p>Level: {{athlete.level}}</p> 
        <p>Age: {{athlete.age}}</p>
        <p>Budget: {{athlete.budget}}</p>
        <p>Description: {{athlete.description}}</p>
        <p>Sport: {{athlete.type}}</p> 
        <p>More: {{athlete.link}} </p>
        <p>Image: <img src='{{athlete.image.url}}'></p>
        
{% endblock %}

app/templates/athlete_list.html
{% extends 'base.html'%}
{% load staticfiles %}

{% block content %}
<!-- Page Content -->
    <div class="container">

        <!-- Marketing Icons Section -->
        <div class="row">
            <div class="col-lg-12" style= 'margin-top: 150px'>
                <h1 class="page-header">
                <font size="6" color="#8B9F3E">CHOOSE YOUR ATHLETE</font>
                    
                </h1>
            </div>     
        </div>

    

    {% for athlete in sport.athlete_set.all %}
        <a href="/athlete_detail/{{athlete.pk}}">{{athlete.name}}</a>  

        <br>
    {% endfor %}
        
      
{% endblock %} 

app/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title> Reyathena - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/modern-business.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
<style type="text/css">
    
a, 
a:hover, 
a:focus, 
.btn:focus {
    text-decoration: none;
    outline: none;
    color: #818181;
    font-size: 20px;
}

.menu-button {
    margin-top: 230px;
}
</style>
    <!-- Navigation -->

<div class="container">
    <div class="row">  
        <div class="col-md-1 menu-button"><a href="/sport_list/">HOME</a></div>
        <div class="col-md-1 menu-button"> <a href="/about_view/">ABOUT</a></div>
        <div class="col-md-1 menu-button"> <a href="/contact/">CONTACT</a></div>
        <div class="col-md-1"></div>
        <div class="col-md-3 center"><img src="{% static 'images/RLogo.jpg' %}"></div>
        <div class="col-md-1 menu-button"><a href="/login_view/">LOGIN</a></div>
        <div class="col-md-1 menu-button"><a href="/signup/">SIGNUP</a></div>
        <div class="col-md-3 menu-button"> 
            <div class="row">
                <div class="col-lg-12">
                    <div class="input-group">
                      <input type="text" class="form-control" placeholder="Search for...">
                      <span class="input-group-btn">
                        <button class="btn btn-default" type="button">Go!</button>
                      </span>
                    </div><!-- /input-group -->
                </div>
            </div> 

        </div>
    </div>
</div> 



{% block content %}


{% endblock %}

<!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Reyathena 2016</p>
                </div>
            </div>
        </footer>

    
    <!-- /.container -->

    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script>
    {% block js %}
    {% endblock %}

</body>

</html>

app/templates/contact.html
{% extends 'base.html'%}
{% load staticfiles %}

{% block content %}
   
       <form role="form" action="" method="post" style= 'margin-top: 200px'>
       <font size="6" color="#8B9F3E">CONTACT US</font>
       
           {% csrf_token %}
           {{ form.as_p }}
           <button type="submit">Submit</button>
       </form>

{% endblock %}  

app/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Modern Business - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/modern-business.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="about.html">About</a>
                    </li>
                    <li>
                        <a href="services.html">Services</a>
                    </li>
                    <li>
                        <a href="contact.html">Contact</a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Portfolio <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="portfolio-1-col.html">1 Column Portfolio</a>
                            </li>
                            <li>
                                <a href="portfolio-2-col.html">2 Column Portfolio</a>
                            </li>
                            <li>
                                <a href="portfolio-3-col.html">3 Column Portfolio</a>
                            </li>
                            <li>
                                <a href="portfolio-4-col.html">4 Column Portfolio</a>
                            </li>
                            <li>
                                <a href="portfolio-item.html">Single Portfolio Item</a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Blog <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="blog-home-1.html">Blog Home 1</a>
                            </li>
                            <li>
                                <a href="blog-home-2.html">Blog Home 2</a>
                            </li>
                            <li>
                                <a href="blog-post.html">Blog Post</a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Other Pages <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="full-width.html">Full Width Page</a>
                            </li>
                            <li>
                                <a href="sidebar.html">Sidebar Page</a>
                            </li>
                            <li>
                                <a href="faq.html">FAQ</a>
                            </li>
                            <li>
                                <a href="404.html">404</a>
                            </li>
                            <li>
                                <a href="pricing.html">Pricing Table</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Header Carousel -->
    <header id="myCarousel" class="carousel slide">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class="item active">
                <div class="fill" style="background-image:url('http://placehold.it/1900x1080&text=Slide One');"></div>
                <div class="carousel-caption">
                    <h2>Caption 1</h2>
                </div>
            </div>
            <div class="item">
                <div class="fill" style="background-image:url('http://placehold.it/1900x1080&text=Slide Two');"></div>
                <div class="carousel-caption">
                    <h2>Caption 2</h2>
                </div>
            </div>
            <div class="item">
                <div class="fill" style="background-image:url('http://placehold.it/1900x1080&text=Slide Three');"></div>
                <div class="carousel-caption">
                    <h2>Caption 3</h2>
                </div>
            </div>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="icon-next"></span>
        </a>
    </header>

    <!-- Page Content -->
    <div class="container">

        <!-- Marketing Icons Section -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                    Welcome to Modern Business
                </h1>
            </div>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4><i class="fa fa-fw fa-check"></i> Bootstrap v3.2.0</h4>
                    </div>
                    <div class="panel-body">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis quae nulla aspernatur in alias at numquam rerum ea excepturi expedita tenetur assumenda voluptatibus eveniet incidunt dicta nostrum quod?</p>
                        <a href="#" class="btn btn-default">Learn More</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4><i class="fa fa-fw fa-gift"></i> Free &amp; Open Source</h4>
                    </div>
                    <div class="panel-body">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis quae nulla aspernatur in alias at numquam rerum ea excepturi expedita tenetur assumenda voluptatibus eveniet incidunt dicta nostrum quod?</p>
                        <a href="#" class="btn btn-default">Learn More</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4><i class="fa fa-fw fa-compass"></i> Easy to Use</h4>
                    </div>
                    <div class="panel-body">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis quae nulla aspernatur in alias at numquam rerum ea excepturi expedita tenetur assumenda voluptatibus eveniet incidunt dicta nostrum quod?</p>
                        <a href="#" class="btn btn-default">Learn More</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.row -->

        <!-- Portfolio Section -->
        <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">Portfolio Heading</h2>
            </div>
            <div class="col-md-4 col-sm-6">
                <a href="portfolio-item.html">
                    <img class="img-responsive img-portfolio img-hover" src="http://placehold.it/700x450" alt="">
                </a>
            </div>
            <div class="col-md-4 col-sm-6">
                <a href="portfolio-item.html">
                    <img class="img-responsive img-portfolio img-hover" src="http://placehold.it/700x450" alt="">
                </a>
            </div>
            <div class="col-md-4 col-sm-6">
                <a href="portfolio-item.html">
                    <img class="img-responsive img-portfolio img-hover" src="http://placehold.it/700x450" alt="">
                </a>
            </div>
            <div class="col-md-4 col-sm-6">
                <a href="portfolio-item.html">
                    <img class="img-responsive img-portfolio img-hover" src="http://placehold.it/700x450" alt="">
                </a>
            </div>
            <div class="col-md-4 col-sm-6">
                <a href="portfolio-item.html">
                    <img class="img-responsive img-portfolio img-hover" src="http://placehold.it/700x450" alt="">
                </a>
            </div>
            <div class="col-md-4 col-sm-6">
                <a href="portfolio-item.html">
                    <img class="img-responsive img-portfolio img-hover" src="http://placehold.it/700x450" alt="">
                </a>
            </div>
        </div>
        <!-- /.row -->

        <!-- Features Section -->
        <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">Modern Business Features</h2>
            </div>
            <div class="col-md-6">
                <p>The Modern Business template by Start Bootstrap includes:</p>
                <ul>
                    <li><strong>Bootstrap v3.2.0</strong>
                    </li>
                    <li>jQuery v1.11.0</li>
                    <li>Font Awesome v4.1.0</li>
                    <li>Working PHP contact form with validation</li>
                    <li>Unstyled page elements for easy customization</li>
                    <li>17 HTML pages</li>
                </ul>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, omnis doloremque non cum id reprehenderit, quisquam totam aspernatur tempora minima unde aliquid ea culpa sunt. Reiciendis quia dolorum ducimus unde.</p>
            </div>
            <div class="col-md-6">
                <img class="img-responsive" src="http://placehold.it/700x450" alt="">
            </div>
        </div>
        <!-- /.row -->

        <hr>

        <!-- Call to Action Section -->
        <div class="well">
            <div class="row">
                <div class="col-md-8">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, expedita, saepe, vero rerum deleniti beatae veniam harum neque nemo praesentium cum alias asperiores commodi.</p>
                </div>
                <div class="col-md-4">
                    <a class="btn btn-lg btn-default btn-block" href="#">Call to Action</a>
                </div>
            </div>
        </div>

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script>

</body>

</html>

app/templates/login_view.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}



    {% csrf_token %}

    {% crispy form %}

   

{% endblock %}

app/templates/signup.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}



  
    {% csrf_token %}

    {% crispy form %}
    

    {% if user.is_authenticated %}

        {{valid}}
        
    {% endif %}
    
     
  
  
  
  

{% endblock %}

app/templates/swimming.html
<html>
<head>
<title>REYATHENA l CONTACT</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link href="Reyathena/Web2/main.css" rel="stylesheet" type="text/css">
<link href="main.css" rel="stylesheet" type="text/css">
</head>
<body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
<!-- Save for Web Slices (About.psd) -->
<table width="1025" height="839" border="0" align="center" cellpadding="0" cellspacing="0" id="Table_01">
	<tr>
		<td colspan="10">
			<img src="images/About_01.png" width="1024" height="3" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="1" height="3" alt=""></td>
	</tr>
	<tr>
		<td colspan="3" rowspan="4">
			<img src="images/About_02.png" width="396" height="147" alt=""></td>
		<td rowspan="8"><a href="index.html"><img src="images/Logo.png" width="212" height="209" alt=""></a></td>
		<td colspan="6">
			<img src="images/About_04.png" width="416" height="63" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="1" height="63" alt=""></td>
	</tr>
	<tr>
		<td colspan="3">
			<img src="images/About_05.png" width="266" height="40" alt=""></td>
		<td colspan="2">
			<img src="images/SM.png" alt="" width="120" height="40" usemap="#FPMap0Map3" border="0">
			<map name="FPMap0Map3"><area target="_blank" href="http://www.twitter.com/reyathena" shape="rect" coords="78,-2,114,82"><area target="_blank" href="http://www.instagram.com/reyathena" shape="rect" coords="39,-2,75,82">
			  <area target="_blank" href="http://www.snapchat.com/reyathena" shape="rect" coords="0,-1,36,83">
	  </map></td>
		<td rowspan="12">
			<img src="images/About_07.png" width="30" height="772" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="1" height="40" alt=""></td>
	</tr>
	<tr>
		<td rowspan="7">
			<img src="images/About_08.png" width="76" height="119" alt=""></td>
		<td width="310" height="42" colspan="4"align="right"><table width="200" border="0">
		  <tr>
		    <td width="140">SIGNIN</td>
		    <td width="50">LOGIN</td>
	      </tr>
	    </table></td>
		<td>
			<img src="images/spacer.gif" width="1" height="42" alt=""></td>
	</tr>
	<tr>
		<td colspan="4" rowspan="2">
			<img src="images/About_10.png" width="310" height="6" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="1" height="2" alt=""></td>
	</tr>
	<tr>
		<td width="376" height="58" colspan="2" rowspan="3"align="left" valign="middle" class="h1"><table width="370" border="0">
		  <tr class="navbar-nav">
		    <td width="101" align="center"><a href="index.html">HOME</a></td>
		    <td width="102" align="center" class="navbar-nav"><a href="about.html">ABOUT</a></td>
		    <td width="153" align="center" class="navbar-nav"><a href="contact.html">CONTACT</a></td>
	      </tr>
      </table></td>
		<td rowspan="5">
			<img src="images/About_12.png" width="20" height="75" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="1" height="4" alt=""></td>
	</tr>
	<tr>
		<td rowspan="4">
			<img src="images/About_13.png" width="3" height="71" alt=""></td>
		<td width="305" height="27" colspan="2">SEARCH
      </td>
		<td rowspan="8">
			<img src="images/About_15.png" width="2" height="684" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="1" height="27" alt=""></td>
	</tr>
	<tr>
		<td colspan="2" rowspan="3">
			<img src="images/About_16.png" width="305" height="44" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="1" height="27" alt=""></td>
	</tr>
	<tr>
		<td colspan="2" rowspan="2">
			<img src="images/About_17.png" width="376" height="17" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="1" height="4" alt=""></td>
	</tr>
	<tr>
		<td>
			<img src="images/About_18.png" width="212" height="13" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="1" height="13" alt=""></td>
	</tr>
	<tr>
		<td rowspan="2">
			<img src="images/About_19.png" width="38" height="563" alt=""></td>
		<td width="954" height="546" colspan="7"><p class="h1">SWIMMING</p>
		  <p class="h1">&nbsp;</p>
	    

    {% for athlete in sport.athlete_set.all %}
        <a href="/athlete_detail/{{athlete.pk}}">{{athlete.name}}</a>  

        <br>
    {% endfor %}
	  <p>&nbsp;</p></td>
		<td>
			<img src="images/spacer.gif" width="1" height="546" alt=""></td>
	</tr>
	<tr>
		<td colspan="7">
			<img src="images/About_21.png" width="954" height="17" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="1" height="17" alt=""></td>
	</tr>
	<tr>
		<td width="376" height="40" colspan="2">Copyright © Reyathena 2016. All Rights Reserved 

      </td>
		<td colspan="6" rowspan="2">
			<img src="images/About_23.png" width="616" height="50" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="1" height="40" alt=""></td>
	</tr>
	<tr>
		<td colspan="2">
			<img src="images/About_24.png" width="376" height="10" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="1" height="10" alt=""></td>
	</tr>
	<tr>
		<td>
			<img src="images/spacer.gif" width="38" height="1" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="338" height="1" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="20" height="1" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="212" height="1" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="76" height="1" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="3" height="1" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="187" height="1" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="118" height="1" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="2" height="1" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="30" height="1" alt=""></td>
		<td></td>
	</tr>
</table>
<!-- End Save for Web Slices -->
</body>
</html>